spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:deliverytestdb;"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1200
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    version: v1.0.0
  packages-to-scan: com.joyuna
  packages-to-exclude:
  paths-to-exclude:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true
---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: "jdbc:mariadb://localhost:3306/deliverytestdb"
    username: "root"
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      hibernate:
        format_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.mariadb106Dialect
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1200
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    version: v1.0.0
  packages-to-scan: com.joyuna
  packages-to-exclude:
  paths-to-exclude:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true