spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:// localhost:3306/deliverytestdb
    username:
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
