spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:deliverytestdb;"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: "jdbc:mariadb://localhost:3306/deliverytestdb"
    username: "root"
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      hibernate:
        format_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.mariadb106Dialect